title: Sinclaire Manning
description: Sinclaire Manning's Professional Website

url: http://smanning3.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Research
   url: /research
 - title: CV
   url: /cv
 - title: Downloads
   url: /downloads
 - title: Contact
   url: /contact

social:
   github: smanning3
#   twitter: bluebarracuda33
#   facebook: Sinclaire Manning
   email: smanning@astro.as.utexas.edu

google_analytics: "UA-58263416-1"
